{% set name = "pytest-metadata" %}
{% set version = "1.9.0" %}
{% set hash = "168d203abba8cabb65cf1b5fa675b0ba60dccbf1825d147960876a7e6f7c219c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.9.0

  run:
    - python
    - setuptools
    - pytest >=2.9.0

test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/davehunt/pytest-metadata
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for test session metadata

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
