{% set name = "pytest-metadata" %}
{% set version = "3.1.1" %}
{% set hash = "d2a29b0355fbc03f168aa96d41ff88b1a3b44a3b02acbe491801c98a048017c8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_metadata-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatch-vcs >=0.3
    - hatchling >=1.13

  run:
    - python >={{ python_min }}
    - pytest >=7.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/pytest-dev/pytest-metadata
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for test session metadata

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
