{% set name = "pytest-metadata" %}
{% set version = "3.0.0" %}
{% set hash = "769a9c65d2884bd583bc626b0ace77ad15dbe02dd91a9106d47fd46d9c2569ca" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_metadata-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry >=1.0.0

  run:
    - python >=3.7
    - pytest >=3.0.0,<8.0.0

test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/pytest-dev/pytest-metadata
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for test session metadata

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
