{% set name = "pytest-metadata" %}
{% set version = "2.0.1" %}
{% set hash = "5cdb6aeea8ba9109181cf9f149c8a3ae1430ff7e44506a8f866af8a98ca46301" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=45.0
    - setuptools_scm >=6.2.3
    - pytest >=2.9.0

  run:
    - python >=3.7
    - pytest >=2.9.0

test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/pytest-dev/pytest-metadata
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: pytest plugin for test session metadata

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
