{% set name = "pytest-metadata" %}
{% set version = "1.7.0" %}
{% set hash_type = "sha256" %}
{% set hash = "2d495b61542cb25dfc52fbf40c7a02220c7c127b7ba8974e6c72d6c9593c547a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - pytest >=2.9.0

  run:
    - python
    - setuptools
    - pytest >=2.9.0

test:
  imports:
    - pytest_metadata
    - pytest_metadata.ci

about:
  home: https://github.com/davehunt/pytest-metadata
  license: MPL 2.0
  license_family: OTHER
  license_file: LICENSE
  summary: 'pytest plugin for test session metadata'

extra:
  recipe-maintainers:
    - birdsarah
    - davehunt
    - nicoddemus
