travis:
  secure:
    BINSTAR_TOKEN: yC4gVyM2akPtlyiHjW3XfT6izFMDARcgqKiBiv8XrmPBUDIaKKgZjYtpzY6IB0Wylo1pTvaa6yVU9TR2YEnW/zk9ilJ5sob/Si18ZoemKMNipGRjRg2rKMumGo7yJfCSKGzmjZQS5secr/tjTHwpKMEzAtDSXVDcDHeJOeiN0GOIhOcNI7vo5IB6OU9+/91FKlIa2sWGe0VETt4v3lDIrCGCi6iyVy6eIAffuFPC7643uUSNxJ6DFQnooJCqCOgnY91Gpt/ApscHllCWMIq9+VipYEwzLb1ZHm3wNTHjv0HPp/4QUkJo/BlmYykcIo3kqsS/UGNv7wj/aYRNIiyQJ2wQQZ7qw7utYbXFMj2RT1zSwSHD82HQqNYfKbux/w1eeGo/xyT0Ll0bMb/MTLXR+gYHLZVmJiMCpcHL9dncgQ1BLlYMZ0TdDjuoU2NSN8d52JZkBqj6RShc+17H5ZEYNKDe/aljTqsGxAGnE/NhlwV9XMt/e1RUSsg5bnI0N9dLIzUex+PJ9Y13tyStbdofUZif2+r5Fu7/ETaVEFi8ZggfmGnVBBgw7qGkGUTbAZyO7nguw883uZgQnt9F7OS/RlT16962OFwHKVdE1axSlxeoEr+gZCxe7tvgqBwafVg1fl8hAmGxOYWuiig9R2ikMK0i6c4Jbtv+ihSI22q/xqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
